/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Cell: typeof import('./components/Cell.vue')['default']
    Confetti: typeof import('./components/Confetti.vue')['default']
    Controller: typeof import('./components/Controller.vue')['default']
    KeyBoard: typeof import('./components/KeyBoard.vue')['default']
    Map: typeof import('./components/Map.vue')['default']
    MineBlock: typeof import('./components/MineBlock.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SnakeCell: typeof import('./components/SnakeCell.vue')['default']
    SnakeController: typeof import('./components/SnakeController.vue')['default']
    SnakeKeyBoard: typeof import('./components/SnakeKeyBoard.vue')['default']
    SnakeMap: typeof import('./components/SnakeMap.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
  }
}
